<?php /** @var \Light\Form\Element\Date $element */ ?>
<?php $element = $this->element; ?>

<input type="text"
       class="bmd-input"
       autocomplete="off"
       data-datepicker="true"
       data-format="<?php echo $element->getFormat(); ?>"
       <?php if ($element->isReadOnly()) : ?>disabled="disabled"<?php endif; ?>
       id="<?php echo $element->getName(); ?>"
       name="<?php echo $element->getName(); ?>"
       <?php if ($element->getValue()) : ?>
         value="<?php echo date($element->getPhpFormat(), $element->getValue()); ?>"
       <?php endif; ?>
       />

<label class="bmd-label"><?php echo $element->getLabel(); ?></label>
<span class="bmd-bar"></span>
